-- Ashen Wolves HUB v1.3 - Agenda
create table if not exists public.agenda_events (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  event_type text not null check (event_type in ('Réunion','Opération','Balade','Événement RP','Recrutement','RDV Crimi','Divers')),
  event_date date not null,
  event_time time not null,
  location text,
  contact text,
  description text,
  participants text,
  status text not null default 'scheduled' check (status in ('scheduled','completed')),
  completed_at timestamptz,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agenda_events enable row level security;

drop policy if exists "agenda public read" on public.agenda_events;
create policy "agenda public read" on public.agenda_events for select to anon, authenticated using (true);

drop policy if exists "agenda public insert" on public.agenda_events;
create policy "agenda public insert" on public.agenda_events for insert to anon, authenticated with check (true);

drop policy if exists "agenda admin update" on public.agenda_events;
create policy "agenda admin update" on public.agenda_events for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "agenda admin delete" on public.agenda_events;
create policy "agenda admin delete" on public.agenda_events for delete to authenticated using (public.is_admin());

create or replace function public.set_agenda_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists agenda_updated_at on public.agenda_events;
create trigger agenda_updated_at before update on public.agenda_events for each row execute function public.set_agenda_updated_at();

-- Compatibilité avec une installation existante
alter table public.agenda_events add column if not exists contact text;
