"use strict";
(() => {
const TYPES={"Réunion":"#7c3aed","Opération":"#dc2626","Balade":"#16a34a","Événement RP":"#d4a017","Recrutement":"#2563eb","RDV Crimi":"#ea580c","Divers":"#64748b"};
let events=[],view="calendar",month=new Date(),admin=false,editing=null;
const $=id=>document.getElementById(id), els={module:$("agenda-module"),add:$("agenda-add"),search:$("agenda-search"),filter:$("agenda-type-filter"),counter:$("agenda-counter"),refresh:$("agenda-refresh"),status:$("agenda-status"),calendar:$("agenda-calendar"),month:$("agenda-month-label"),list:$("agenda-list"),archives:$("agenda-archives"),dialog:$("agenda-dialog"),form:$("agenda-form"),detailDialog:$("agenda-detail-dialog"),detail:$("agenda-detail")};
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function localDateKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`}
function dateKey(e){return `${e.event_date}T${e.event_time||"00:00"}`}
function isArchived(e){return e.status==="completed" || new Date(dateKey(e))<new Date();}
function filtered(archive=false){const q=els.search.value.trim().toLowerCase(),t=els.filter.value;return events.filter(e=>isArchived(e)===archive).filter(e=>!t||e.event_type===t).filter(e=>!q||[e.title,e.event_type,e.location,e.description,e.participants,e.event_date].some(x=>String(x||"").toLowerCase().includes(q))).sort((a,b)=>dateKey(a).localeCompare(dateKey(b)));}
function fmtDate(d){return new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date(d+"T12:00"));}
function render(){document.querySelectorAll(".agenda-view").forEach(x=>x.hidden=true);$("agenda-"+view+"-view").hidden=false;document.querySelectorAll("[data-agenda-view]").forEach(b=>b.classList.toggle("is-active",b.dataset.agendaView===view));if(view==="calendar")renderCalendar();if(view==="list")renderList(els.list,false);if(view==="archives")renderList(els.archives,true);const n=filtered(view==="archives").length;els.counter.textContent=`${n} événement${n>1?"s":""}`;}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth();els.month.textContent=new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(month);const first=new Date(y,m,1),start=new Date(y,m,1-((first.getDay()+6)%7));let html="";for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=localDateKey(d),outside=d.getMonth()!==m,today=key===localDateKey();const dayEvents=filtered(false).filter(e=>e.event_date===key);html+=`<article class="agenda-day ${outside?'is-outside':''} ${today?'is-today':''}"><div class="agenda-day-number">${d.getDate()}</div><div class="agenda-day-events">${dayEvents.slice(0,4).map(e=>`<button class="agenda-event-chip" data-event-id="${e.id}" style="--event-color:${TYPES[e.event_type]||TYPES.Divers}">${esc(e.event_time?.slice(0,5)||"")} ${esc(e.title)}</button>`).join("")}${dayEvents.length>4?`<small>+ ${dayEvents.length-4} autre(s)</small>`:""}</div></article>`}els.calendar.innerHTML=html;}
function renderList(target,archive){const rows=filtered(archive);if(!rows.length){target.innerHTML='<div class="agenda-empty">Aucun événement à afficher.</div>';return;}target.innerHTML=rows.map(e=>{const d=new Date(e.event_date+"T12:00");return `<article class="agenda-card" style="--event-color:${TYPES[e.event_type]||TYPES.Divers}"><div class="agenda-card-date"><strong>${d.getDate()}</strong><span>${new Intl.DateTimeFormat("fr-FR",{month:"short"}).format(d)}</span></div><div><h3>${esc(e.title)}</h3><div class="agenda-card-meta">${esc(e.event_type)} · ${esc((e.event_time||"").slice(0,5))}${e.location?` · ${esc(e.location)}`:""}</div></div><div class="agenda-card-actions"><button data-event-id="${e.id}">Voir</button>${admin&&!archive?`<button data-edit-id="${e.id}">Modifier</button><button data-complete-id="${e.id}">Terminer</button>`:""}${admin?`<button data-delete-id="${e.id}">Supprimer</button>`:""}</div></article>`}).join("");}
async function detectAdmin(){try{const {data:{session}}=await supabaseClient.auth.getSession();if(!session){admin=false;return;}const {data}=await supabaseClient.rpc("is_admin");admin=Boolean(data)&&!(typeof visitorMode!=="undefined"&&visitorMode);}catch{admin=false;}}
async function load(){els.status.textContent="Actualisation…";els.refresh.disabled=true;try{const {data,error}=await supabaseClient.from("agenda_events").select("*").order("event_date").order("event_time");if(error)throw error;events=data||[];els.status.textContent="";render();}catch(e){els.status.textContent="Impossible de charger l’agenda. Vérifie que AGENDA_SETUP.sql a été exécuté.";console.error(e);}finally{els.refresh.disabled=false;}}
function openForm(e=null){editing=e?.id||null;$("agenda-dialog-title").textContent=e?"Modifier l’événement":"Ajouter un événement";$("agenda-event-title").value=e?.title||"";$("agenda-event-type").value=e?.event_type||"Réunion";$("agenda-location").value=e?.location||"";$("agenda-date").value=e?.event_date||localDateKey();$("agenda-time").value=(e?.event_time||"20:00").slice(0,5);$("agenda-participants").value=e?.participants||"";$("agenda-description").value=e?.description||"";$("agenda-form-error").hidden=true;els.dialog.showModal();}
async function save(ev){ev.preventDefault();const payload={title:$("agenda-event-title").value.trim(),event_type:$("agenda-event-type").value,event_date:$("agenda-date").value,event_time:$("agenda-time").value,location:$("agenda-location").value.trim()||null,participants:$("agenda-participants").value.trim()||null,description:$("agenda-description").value.trim()||null};try{let q=editing?supabaseClient.from("agenda_events").update(payload).eq("id",editing):supabaseClient.from("agenda_events").insert(payload);const {error}=await q;if(error)throw error;els.dialog.close();await load();}catch(e){$("agenda-form-error").textContent=e.message||"Enregistrement impossible.";$("agenda-form-error").hidden=false;}}
function showDetail(e){els.detail.innerHTML=`<div class="agenda-dialog-head"><div><span class="agenda-type-badge" style="--event-color:${TYPES[e.event_type]||TYPES.Divers}">${esc(e.event_type)}</span><h2>${esc(e.title)}</h2></div><button data-close-detail>×</button></div><div class="agenda-detail-row"><strong>Date :</strong> ${esc(fmtDate(e.event_date))} à ${esc((e.event_time||"").slice(0,5))}</div>${e.location?`<div class="agenda-detail-row"><strong>Lieu :</strong> ${esc(e.location)}</div>`:""}${e.participants?`<div class="agenda-detail-row"><strong>Participants :</strong> ${esc(e.participants)}</div>`:""}${e.description?`<div class="agenda-detail-row"><strong>Description :</strong><br>${esc(e.description).replace(/\n/g,"<br>")}</div>`:""}<div class="agenda-detail-actions">${admin&&!isArchived(e)?`<button data-edit-id="${e.id}">Modifier</button><button data-complete-id="${e.id}">Terminer</button>`:""}${admin?`<button data-delete-id="${e.id}">Supprimer</button>`:""}</div>`;els.detailDialog.showModal();}
async function complete(id){const {error}=await supabaseClient.from("agenda_events").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",id);if(error)alert(error.message);else{els.detailDialog.close();load();}}
async function remove(id){if(!confirm("Supprimer définitivement cet événement ?"))return;const {error}=await supabaseClient.from("agenda_events").delete().eq("id",id);if(error)alert(error.message);else{els.detailDialog.close();load();}}
function delegated(e){const id=e.target.dataset.eventId||e.target.dataset.editId||e.target.dataset.completeId||e.target.dataset.deleteId;if(!id)return;const item=events.find(x=>String(x.id)===String(id));if(e.target.dataset.eventId&&item)showDetail(item);if(e.target.dataset.editId&&item){els.detailDialog.close();openForm(item);}if(e.target.dataset.completeId)complete(id);if(e.target.dataset.deleteId)remove(id);}
Object.keys(TYPES).forEach(t=>{els.filter.add(new Option(t,t));$("agenda-event-type").add(new Option(t,t));});document.querySelectorAll("[data-agenda-view]").forEach(b=>b.onclick=()=>{view=b.dataset.agendaView;render();});els.add.onclick=()=>openForm();els.refresh.onclick=load;els.search.oninput=render;els.filter.onchange=render;$("agenda-prev-month").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);render()};$("agenda-next-month").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);render()};$("agenda-dialog-close").onclick=$("agenda-cancel").onclick=()=>els.dialog.close();[els.dialog,els.detailDialog].forEach(dialog=>dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()}));els.form.addEventListener("submit",save);els.calendar.addEventListener("click",delegated);els.list.addEventListener("click",delegated);els.archives.addEventListener("click",delegated);els.detail.addEventListener("click",e=>{if(e.target.dataset.closeDetail!==undefined)els.detailDialog.close();delegated(e)});window.addEventListener("hub:agenda-visible",async()=>{await detectAdmin();load()});if(window.supabaseClient?.auth)supabaseClient.auth.onAuthStateChange(async()=>{await detectAdmin();render()});
})();
