"use strict";
(()=>{
 const page=document.getElementById("amendes-module");if(!page)return;const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 let fines=[],members=[],records=[],loaded=false;const today=()=>new Date().toISOString().slice(0,10);const money=v=>Number(v||0).toLocaleString("fr-FR")+" $";const date=v=>v?new Intl.DateTimeFormat("fr-FR").format(new Date(v+"T12:00:00")):"—";
 function activeRows(name){return records.filter(r=>r.member_first_name===name&&r.recurrence_until&&r.recurrence_until>=today())}function status(name){const count=new Set(activeRows(name).map(r=>r.fine_id)).size;return count>1?["Récidives multiples","is-multiple"]:count===1?["Récidive","is-single"]:["Pas de récidive",""]}
 async function load(force=false){if(loaded&&!force)return render();const [a,b,c]=await Promise.all([supabaseClient.from("fine_catalogue").select("*").order("category").order("sort_order"),supabaseClient.from("directory_members").select("first_name,last_name,identity_name").order("sort_order"),supabaseClient.from("member_fines").select("*, fine_catalogue(title,category,amount)").order("fine_date",{ascending:false})]);if(a.error||b.error||c.error){console.error(a.error||b.error||c.error);$("amendes-catalogue").innerHTML='<p class="amendes-empty">Module non installé. Exécute AMENDES_SETUP.sql dans Supabase.</p>';return}fines=a.data||[];members=b.data||[];records=c.data||[];loaded=true;fillForm();render()}
 function render(){renderCatalogue();renderMembers();renderHistory();const route=decodeURIComponent(location.hash.split("/")[2]||"");if(route)openRecord(route)}
 function renderCatalogue(){const q=$("amendes-catalogue-search").value.trim().toLowerCase();$("amendes-catalogue").innerHTML=[1,2,3,4].map(cat=>{const rows=fines.filter(f=>f.category===cat&&(!q||f.title.toLowerCase().includes(q)));return `<section class="amendes-category"><h2>Catégorie ${cat}</h2>${rows.length?rows.map(f=>`<div class="amendes-fine"><span>${esc(f.title)}</span><strong>${money(f.amount)}</strong></div>`).join(""):'<p class="amendes-empty">Aucun résultat.</p>'}</section>`}).join("")}
 function renderMembers(){const q=$("amendes-member-search").value.trim().toLowerCase();const list=members.filter(m=>!q||m.first_name.toLowerCase().includes(q));$("amendes-members").innerHTML=list.map(m=>{const [label,cls]=status(m.first_name),last=records.find(r=>r.member_first_name===m.first_name);return `<a class="amendes-member-card" href="#/amendes/${encodeURIComponent(m.first_name)}"><h3>${esc(m.first_name)}</h3><span class="amendes-status ${cls}">${label}</span><div class="amendes-card-last">${last?`Dernière amende : <strong>${esc(last.fine_catalogue?.title||"")}</strong><br>${date(last.fine_date)}`:"Aucune amende enregistrée"}</div></a>`}).join("")||'<p class="amendes-empty">Aucun membre.</p>'}
 function filtered(){const q=$("amendes-history-search").value.trim().toLowerCase(),cat=$("amendes-history-category").value,paid=$("amendes-history-paid").value,rec=$("amendes-history-recurrence").value,d=$("amendes-history-date").value;return records.filter(r=>(!q||[r.member_first_name,r.fine_catalogue?.title].some(x=>String(x||"").toLowerCase().includes(q)))&&(cat==="all"||String(r.fine_catalogue?.category)===cat)&&(paid==="all"||String(r.paid)===paid)&&(!d||r.fine_date===d)&&(rec==="all"||(rec==="active")===(r.recurrence_until>=today())))}
 function historyHtml(rows){return rows.map(r=>`<article class="amendes-history-row"><div><strong>${esc(r.member_first_name)}</strong><br><small>${date(r.fine_date)}</small></div><div><strong>${esc(r.fine_catalogue?.title||"Infraction supprimée")}</strong><br><small>Catégorie ${r.fine_catalogue?.category||"—"}</small></div><strong>${money(r.amount_charged||r.fine_catalogue?.amount)}</strong><span class="amendes-paid ${r.paid?'':'is-unpaid'}">${r.paid?'Payée':'Impayée'}</span><span>${r.recurrence_until>=today()?`Récidive jusqu’au ${date(r.recurrence_until)}`:"Pas de récidive"}</span><button class="amendes-secondary" data-fine-delete="${r.id}">×</button></article>`).join("")||'<p class="amendes-empty">Aucune amende.</p>'}
 function renderHistory(){$("amendes-history").innerHTML=historyHtml(filtered());$("amendes-history").querySelectorAll("[data-fine-delete]").forEach(b=>b.onclick=()=>remove(b.dataset.fineDelete))}
 function openRecord(name){show("record");const rows=records.filter(r=>r.member_first_name.toLowerCase()===name.toLowerCase()),[label,cls]=status(name),sum=rows.reduce((a,r)=>a+Number(r.amount_charged||r.fine_catalogue?.amount||0),0);$("amendes-record").innerHTML=`<div class="amendes-record-head"><div><p>Casier judiciaire</p><h1>${esc(name.toUpperCase())}</h1></div><span class="amendes-status ${cls}">${label}</span></div><div class="amendes-summary"><article><span>Total d’amendes</span><strong>${rows.length}</strong></article><article><span>Montant cumulé</span><strong>${money(sum)}</strong></article><article><span>Dernière amende</span><strong>${rows[0]?esc(rows[0].fine_catalogue?.title||"—"):"—"}</strong></article></div><div class="amendes-history">${historyHtml(rows)}</div>`;$("amendes-record").querySelectorAll("[data-fine-delete]").forEach(b=>b.onclick=()=>remove(b.dataset.fineDelete))}
 function show(tab){page.querySelectorAll(".amendes-view").forEach(v=>v.hidden=v.id!==`amendes-${tab}-view`);page.querySelectorAll("[data-amendes-tab]").forEach(b=>b.classList.toggle("is-active",b.dataset.amendesTab===tab));if(tab!=="record"&&location.hash.split("/").length>2)history.replaceState(null,"","#/amendes")}
 function fillForm(){$("amendes-member-list").innerHTML=members.map(m=>`<option value="${esc(m.first_name)}"></option>`).join("");$("amendes-form-fine").innerHTML='<option value="">Choisir une infraction…</option>'+fines.map(f=>`<option value="${f.id}">Cat. ${f.category} — ${esc(f.title)} — ${money(f.amount)}</option>`).join("")}
 async function save(e){e.preventDefault();const fine=fines.find(f=>String(f.id)===$("amendes-form-fine").value),member=$("amendes-form-member").value.trim();if(!fine||!member)return;const paid=$("amendes-form-paid").checked,fd=$("amendes-form-date").value;const end=new Date(fd+"T12:00:00");end.setDate(end.getDate()+Number(fine.recurrence_days||0));const {error}=await supabaseClient.from("member_fines").insert({member_first_name:member,fine_id:fine.id,fine_date:fd,paid,paid_date:paid?($("amendes-form-paid-date").value||fd):null,recurrence_until:fine.recurrence_days?end.toISOString().slice(0,10):null,amount_charged:fine.amount,notes:$("amendes-form-notes").value.trim()||null});if(error){$("amendes-form-error").hidden=false;$("amendes-form-error").textContent=error.message;return}$("amendes-dialog").close();loaded=false;await load(true)}
 async function remove(id){if(!confirm("Supprimer cette amende du casier ?"))return;const{error}=await supabaseClient.from("member_fines").delete().eq("id",id);if(error)return alert(error.message);loaded=false;await load(true)}
 page.querySelectorAll("[data-amendes-tab]").forEach(b=>b.onclick=()=>show(b.dataset.amendesTab));$("amendes-add").onclick=()=>{$("amendes-form").reset();$("amendes-form-date").value=today();$("amendes-form-paid-date").value=today();$("amendes-form-error").hidden=true;$("amendes-dialog").showModal()};page.querySelectorAll("[data-amendes-close]").forEach(b=>b.onclick=()=>$("amendes-dialog").close());$("amendes-dialog").onclick=e=>{if(e.target===$("amendes-dialog"))$("amendes-dialog").close()};$("amendes-form").onsubmit=save;["amendes-catalogue-search","amendes-member-search","amendes-history-search"].forEach(id=>$(id).oninput=render);["amendes-history-category","amendes-history-paid","amendes-history-recurrence","amendes-history-date"].forEach(id=>$(id).onchange=renderHistory);window.addEventListener("hub:fines-visible",()=>load());
})();
