create table if not exists public.fine_catalogue (
  id bigint generated by default as identity primary key,
  category smallint not null check (category between 1 and 4),
  title text not null unique,
  amount numeric(12,2) not null check (amount >= 0),
  recurrence_days integer not null default 7 check (recurrence_days >= 0),
  sort_order integer not null default 0
);
create table if not exists public.member_fines (
  id bigint generated by default as identity primary key,
  member_first_name text not null,
  fine_id bigint not null references public.fine_catalogue(id),
  fine_date date not null default current_date,
  paid boolean not null default true,
  paid_date date,
  recurrence_until date,
  amount_charged numeric(12,2) not null,
  notes text,
  created_at timestamptz not null default now()
);
alter table public.fine_catalogue enable row level security;
alter table public.member_fines enable row level security;
drop policy if exists "fine catalogue read" on public.fine_catalogue; create policy "fine catalogue read" on public.fine_catalogue for select using (true);
drop policy if exists "member fines read" on public.member_fines; create policy "member fines read" on public.member_fines for select using (true);
drop policy if exists "member fines insert" on public.member_fines; create policy "member fines insert" on public.member_fines for insert with check (true);
drop policy if exists "member fines update" on public.member_fines; create policy "member fines update" on public.member_fines for update using (true) with check (true);
drop policy if exists "member fines delete" on public.member_fines; create policy "member fines delete" on public.member_fines for delete using (true);
grant select on public.fine_catalogue to anon, authenticated; grant select,insert,update,delete on public.member_fines to anon, authenticated; grant usage,select on all sequences in schema public to anon,authenticated;
insert into public.fine_catalogue(category,title,amount,sort_order) values
(1,'Rappel à la loi',450,1),(1,'Infraction aux règles de circulation',500,2),(1,'Permis ou licence manquant',600,3),(1,'Dégradation/Destruction de Poubelle',900,4),(1,'Participation à un événement illégal',900,5),(1,'Vol',1300,6),(1,'Trouble à l''ordre public',1500,7),(1,'Insulte ou outrage',2200,8),(1,'Commerce illégal',2500,9),(1,'Intrusion illégale sur propriété privée',2500,10),
(2,'Détention d''objets prohibés',1600,1),(2,'Extorsion',1750,2),(2,'Dégradation de bien public et/ou privé',2300,3),(2,'Refus d''obtempérer',2500,4),(2,'Braconnage / Cruauté sur animal',2500,5),(2,'Manquement aux obligations du serment',2500,6),(2,'Mise en danger d''autrui',3000,7),(2,'Organisation d''événement illégal',3200,8),(2,'Braquage de commerce local/cambriolage',3500,9),(2,'Port d''arme illégal',4000,10),(2,'Atteinte à l''intégrité morale et/ou physique',5000,11),(2,'Intrusion illégale sur propriété publique',5000,12),(2,'Trafic de stupéfiants',5500,13),(2,'Vol aggravé',10000,14),
(3,'Divulgation et/ou vol d''informations confidentielles',6000,1),(3,'Usurpation d''identité et/ou impersonation',6000,2),(3,'Diffamation',7000,3),(3,'Atteinte au bon fonctionnement d’une entreprise',9000,4),(3,'Obstruction à la justice',10000,5),(3,'Tentative de corruption',10000,6),(3,'Atteinte à l''intégrité morale armée',12000,7),(3,'Parjure ou faux témoignage',12000,8),(3,'Détention de matériel militaire et/ou armement lourd prohibé',13000,9),(3,'Perturbation au sein d’un tribunal',14000,10),(3,'Cybercriminalité',15000,11),(3,'Trafic et/ou contrebande',15000,12),(3,'Atteinte à l''intégrité physique armée',18000,13),(3,'Menace ou atteinte contre agent public',20000,14),(3,'Braquage de plateforme pétrolière/Yacht',20000,15),
(4,'Corruption ou chantage',25000,1),(4,'Fraude/Blanchiment d’argent',25000,2),(4,'Enlèvement ou prise d''otage',25000,3),(4,'Violation de serment',30000,4),(4,'Attaque à main armée aggravée',40000,5),(4,'Perturbation de San Andreas',40000,6),(4,'Tentative d’homicide',50000,7),(4,'Homicide involontaire',75000,8),(4,'Homicide volontaire',150000,9),(4,'Mise en péril des infrastructures étatiques',200000,10),(4,'Mise en péril des représentants étatiques',250000,11),(4,'Homicide sur représentants étatiques',500000,12)
on conflict(title) do update set category=excluded.category,amount=excluded.amount,sort_order=excluded.sort_order;
