-- Données initiales transmises pour l’annuaire des personnes rencontrées
with seed(job, entity, first_name, last_name, nickname, phone, address, notes, relation, contacted_by) as (
 values
  ('BAUN', null, 'Eddy', 'ALVARADO GARCIA', null, '8656', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Harry', 'BAVISTA', null, '4860', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Alphonse', 'BERGER', null, '7854', '11 - HILLCREST AVENUE', 'drogues & cigarettes', 'Gérant de bar', 'Silas'),
  ('BAUN', null, 'Ninon', 'CHEVALIER', null, '0060', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Simeon', 'GELASHVILI', null, '4358', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Mateo', 'HERRERA DEL HUERTO', null, '2681', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Adam', 'MCCORNNICK', null, '7433', null, null, 'Patron', 'Silas'),
  ('BAUN', null, 'Mako', 'MORITA', null, '1130', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Lola', 'MURILLO', null, '6323', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Valentina', 'NAVARRO', null, '7740', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Sancho', 'RAMIREZ', null, '9534', 'BAY CITY AVENUE/VITUS STREET', 'Moto +', 'Collègue', 'Silas'),
  ('BAUN', null, 'Sierra', 'SANDOVAL', null, '8355', null, null, 'Patron', 'Silas'),
  ('BAUN', null, 'Deacon', 'STARK', null, '5191', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Bram', 'STERLING', null, '3796', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Isaac', 'ZAMBRANO IZQUIERDA', '2 Izi', '7270', null, null, 'Collègue', 'Silas'),
  ('BAUN', null, 'Elara', 'CASTELLAS', null, '8711', null, null, 'Collègue', 'Silas'),
  ('BB', null, 'Florian', 'FAREL', null, '8410', null, null, 'Récup stonks', 'Raven'),
  ('BB', null, 'Clyde', 'GRAVES', null, '3932', null, null, 'Récup stonks', 'Raven'),
  ('BB', null, 'David', 'LAMB', null, '6852', '08 - PEACEFULSTREET', null, 'Récup stonks', 'Raven'),
  ('BB', null, 'Fletcher', 'Hathaway', null, '7616', null, null, null, 'Raven'),
  ('BB', null, 'Lillou', '???', null, '1854', null, null, 'Récup stonks', 'Raven'),
  ('BB', null, 'Garance', 'MONTESSORI', null, '2874', null, null, null, 'Raven'),
  ('CASINO', null, 'Kami', 'OKANE', null, '0228', null, null, 'Directeur casino', 'Raven'),
  ('CJR', null, 'Kévin', '???', null, '0921', null, null, null, 'Silas'),
  ('CJR', null, 'Hélios', 'BIAS', null, '4336', null, 'groupe moto japonaise ? ', null, 'Raven'),
  ('CJR', null, 'Jefray', 'DUBOIS', null, '4023', '04 NICOLA PLACE', null, 'Patron', 'Raven'),
  ('CJR', null, 'Nina', 'Agilha-Ashford', null, '8172', null, 'récup stonks', 'Patronne', 'Raven'),
  ('CJR', null, 'Peyo', null, null, '5497', null, null, null, 'Raven'),
  ('STONKS', null, 'Reid', 'ALDRIDGE', null, '8264', null, 'ancien bsco', 'Formation', 'Raven'),
  ('CM', null, 'Julie', 'DÉDIALÉ', null, '4493', null, 'récup stonks', 'Adjointe', 'Raven'),
  ('CM', null, 'Alana', 'MARCH', null, '6646', null, 'récup stonks', 'Patron.ne', 'Raven'),
  ('CM', null, 'Tane', 'MORGAN', null, '1279', null, 'récup stonks', null, 'Raven'),
  ('CM', null, 'Aédan', 'PERLAUT', null, '9798', null, 'récup stonks', 'Patron.ne', 'Raven'),
  ('CJR', null, 'Jack', 'PACKER', null, '3003', null, null, null, 'Raven'),
  ('CM', null, 'Chuck', 'MORITZ', null, '6106', null, null, null, 'Raven'),
  ('DMC', 'FROST', 'Joshua', '???', null, '3331', '11 - ECLIPSE BOULEVARD WEST', null, null, 'Raven'),
  ('DMC', 'FROST', 'Lexie', 'WHITE', null, '9356', null, null, null, 'Raven'),
  ('CM', null, 'Edan', null, null, null, null, null, 'Patron ?', 'Raven'),
  ('DMC', 'FROST', 'Zoé', 'WHITE', null, '7129', '09 - ECLIPSE BOULEVARD WEST', 'N1', null, 'Raven'),
  ('DMC', null, 'Adam', 'STRICKLAND', null, '0771', null, null, 'Patron', 'Raven'),
  ('GOUV', null, '???', '???', null, '3328', null, null, null, 'Silas'),
  ('GOUV', null, 'W.Iliam (qui a rempli)', 'BRADFORD', null, '9762', null, 'récup stonks', null, 'Raven'),
  ('GOUV', null, '???', 'PORTER', null, '8236', null, 'GOUVERNEUR', 'Récup stonks', 'Raven'),
  ('GOUV', null, 'Aleck', 'PRICE', null, '3872', null, null, null, 'Raven'),
  ('LSMC', null, '???', '???', null, '4373', null, 'récup stonk', null, 'Raven'),
  ('DMC', 'FROST', 'Jayden', '???', null, '9041', '11 - ECLIPSE BOULEVARD WEST', null, null, 'Raven'),
  ('GOUV', null, 'Jessy', 'TRINKET', null, '3527', null, null, null, 'Raven'),
  ('LSMC', null, 'Jalen', 'BLAZE', null, '9783', null, null, null, 'Raven'),
  ('LSMC', null, 'Sophie', 'BLOOM', null, '4663', null, null, null, 'Raven'),
  ('LSMC', null, 'Lio', 'FALLS', null, '4285', null, null, 'Récup stonks', 'Raven'),
  ('LSMC', null, 'Rin', 'MONROE', null, '8521', '14 - MOVIE STAR WAY', null, null, 'Raven'),
  ('LSMC', null, 'Kai', 'MONROE', null, '2040', '14 - MOVIE STAR WAY', null, null, 'Raven'),
  ('LSMC', null, 'Malik', 'WINSTON', null, '8099', null, null, null, 'Raven'),
  ('LSMC', null, 'Alex', 'MORGAN', null, '8654', null, 'coupe mulet médecin à chier ?', null, null),
  ('MAIRIE', null, 'Ellis', 'ANDREWS', null, '0345', 'MÊME BATIMENT QUE LE CH', null, null, 'Raven'),
  ('MAIRIE', null, 'Stanley', 'CLARKS', null, '1304', null, 'récup stonks', 'Mairie de paleto', 'Raven'),
  ('MDR', null, 'Théo', 'MAGUEDON', null, '8488', null, 'prosecutor', null, 'Raven'),
  ('MDR', null, 'Marc', 'VANDER LEINO', null, '1543', null, 'JUDGE', 'Prosecutor', null),
  ('MDR', null, 'Larry', 'STARK', null, '3615', null, 'prosecutor', null, null),
  ('MDR', null, 'Michael', 'SMITH', null, '9720', null, 'JUDGE', null, null),
  ('MDR', null, 'Austin', 'GRANT', null, '7041', null, 'JUDGE', null, null),
  ('MDR', null, 'Erika', 'COOPER', null, '3996', null, 'lawyer', null, null),
  ('MDR', null, 'Sean', 'HENSLEY', null, '7658', null, 'lawyer', null, null),
  ('MDR', null, 'Soledad', 'ASTON', null, '9669', null, 'lawyer', null, null),
  ('LSMC', null, null, 'CHEVRENKOV.', null, '1211', null, null, null, 'Raven'),
  ('LSMC', null, 'Alex', 'HUNTER', null, '0738', null, 'Récup stonks', null, 'Raven'),
  ('MDR', null, 'Kon', 'CASTLE', null, '4867', null, 'lawyer', null, null),
  ('MDR', null, 'Giulia', 'COSTELLO', null, '1256', null, 'indépendante', null, null),
  ('MTP', null, '???', '???', null, '???', null, null, 'Pompiste', 'Mason'),
  ('MTP', null, 'Gilbert', 'BRANDOUIN', null, '3134', null, null, 'Pompiste expert', 'Mason'),
  ('MTP', null, 'Mehmet', 'KAYA', null, '1991', null, 'MC / drogue', 'RCEP - Formateur', 'Mason'),
  ('MTP', null, 'William', 'LOCKWOOD', null, '4998', null, null, 'Patron', 'Mason'),
  ('MTP', null, 'Jenna', 'ASHCROFT', null, '7099', null, null, 'Pompiste', 'Mason'),
  ('MTP', null, 'Tim', 'CLARK', null, '3455', null, null, 'Directeur N2', 'Mason'),
  ('MTP', null, 'Arthéon', 'GREY', null, '6420', null, null, 'RCEP - Formateur', 'Mason'),
  ('MTP', null, 'Théo', 'LIVIER', null, '5915', null, null, 'Directeur N2', 'Mason'),
  ('MTP', null, 'Joey', 'FRITZ', null, '9018', null, null, 'Pompiste Confirmé', 'Mason'),
  ('MTP', null, 'Kyle', 'LADOS', null, '4929', null, null, 'Pompiste Sénior', 'Mason'),
  ('MTP', null, 'Leo', 'VILLENEUVE', null, '3652', null, null, 'Pompiste Sénior', 'Mason'),
  ('MTP', null, 'Steven', 'SANDOVAL', null, '5632', null, 'bourre pif', 'Pompiste Sénior', 'Mason'),
  ('MTP', null, 'Rod', 'WOOD', null, '5342', null, null, 'Pompiste', 'Mason'),
  ('NG', null, 'Alberto', 'BROOKS-FREDUCCI', null, '7881', null, null, 'Patron', 'Raven'),
  ('NG', null, 'Marc', 'CHABOT', null, '5621', null, null, 'Directeur', 'Silas'),
  ('NG', null, 'Eric', 'FOSTER', null, '4555', null, null, null, 'Raven'),
  ('STAND-BY', '88', 'Dean', 'WARD', null, '6817', null, 'Criminel', null, 'Raven'),
  ('STAND-BY', null, null, null, null, '8653', null, null, null, null),
  ('PAWL', null, 'Hank', null, null, null, null, null, 'Patron', null),
  ('STAND-BY', 'Obsidian', 'Rico', '???', null, null, null, 'obsidian', null, 'Raven'),
  ('BB', null, 'Ethan', 'MILLER', null, '1251', null, null, null, 'Raven'),
  ('STAND-BY', null, 'Diego', '???', null, null, null, 'obsidian ?', null, 'Raven'),
  ('DMC', null, 'Gregory', 'HERMANOFF', null, '3965', 'PINK CAGE MOTEL', 'Aime la moto / nouvelle arrivant / Demander si on était un MC', null, 'Silas'),
  ('NG', null, 'Rafael', 'IBARA', 'Rafa', '2647', null, 'Moto ?', 'Mécano nocturne', 'Raven'),
  ('BAUN', null, 'Kevon', 'COLE', null, '7288', null, null, null, 'Raven'),
  ('STAND-BY', null, 'Circé', '???', null, null, null, 'obsidian ?', null, 'Raven'),
  ('STAND-BY', null, 'Eddy', 'BARRA', null, null, null, 'Sénateur', null, null),
  ('STAND-BY', null, 'Benedict', 'BRADFORD', null, '???', null, null, 'Sénateur', null),
  ('STAND-BY', null, 'Tyler', 'BROOKS', null, '7064', null, null, null, 'Raven'),
  ('STAND-BY', null, 'Gil', 'CARNOY-DEMUNIER', null, '7687', null, 'récup stonks', 'Sénateur', 'Raven'),
  ('STAND-BY', null, 'Cade', 'LLEWELLYN', null, '3324', null, null, 'Collègue', 'Raven'),
  ('STAND-BY', null, 'Théam', 'SPENTA', null, '4055', null, null, null, null),
  ('STONKS', null, 'Walter', 'BEAR', null, '0215', null, null, 'Sénior', 'Raven'),
  ('STONKS', null, 'Gunnar', 'BJØRNSOND', null, '8292', null, null, null, 'Raven'),
  ('STONKS', null, 'Alexandre', 'BLANCHARD', null, '1903', null, null, 'Sénior', 'Raven'),
  ('DMC', 'FROST', 'Zed', 'NOK', null, '7685', null, null, null, 'Raven'),
  ('CJR', null, 'Matthew', 'ONTIVEROS', null, '8139', null, null, null, 'Raven'),
  ('STAND-BY', null, 'Chris', 'TALE', null, '2905', null, 'Sénateur', null, null),
  ('LSMC', null, '???', '???', null, '0018', null, null, null, 'Raven'),
  ('BB', null, 'Thomas', 'CHANEY', null, '4410', '09 - PEACEFULSTREET', null, null, 'Raven'),
  ('DMC', null, 'Logan', 'PIERARD', null, '9417', null, 'Sénateur', 'Récup stonk resp ou', 'Raven'),
  ('CJR', null, 'Victor', 'DELACROIX', null, '5536', null, null, null, 'Raven'),
  ('NG', null, 'Lucy', 'TORRENTS', null, '2826', null, null, 'Directrice', null),
  ('BAUN', null, 'Jessy', 'COLSON', null, '4583', null, null, 'Collègue', 'Raven'),
  ('BB', null, 'Arthur', null, null, null, '10 - PEACEFULSTREET', null, null, null),
  ('CJR', null, 'Alden', 'KIRKMAN', null, '3383', null, null, 'Test', 'Raven'),
  ('BB', null, 'Nelson', 'ACADIAN', null, '7000', null, null, null, null),
  ('MTP', null, '???', '???', null, '???', null, null, 'Pompiste', 'Mason'),
  ('STONKS', null, 'Gin', 'LLEWELLYN', null, '4261', null, null, 'Junior', 'Raven'),
  ('MTP', null, 'Eron', 'CALVETTI', null, '3775', null, null, 'Pompiste', 'Mason'),
  ('STONKS', null, 'Austin', 'DANIELSON', null, '9249', null, null, 'Administrateur', 'Raven'),
  ('STONKS', null, 'Victoria', 'HOWEN', null, '1644', null, null, null, 'Raven'),
  ('STONKS', null, 'Bryan', 'MONTERRA', null, '1803', null, null, 'Chef d''équipe', 'Raven'),
  ('STONKS', null, 'Luis', 'MONTERRA', null, '1850', null, null, null, 'Raven'),
  ('DMC', 'FROST', 'Vitaly', 'VOSS', null, '5458', '12 - ECLIPSE BOULEVARD WEST', null, null, 'Raven'),
  ('STONKS', null, 'Sean', 'O''CONNOR', null, '7334', null, null, null, 'Raven'),
  ('STONKS', null, 'Benjapol', 'POUPOUNE', 'Benjapawl', '7517', '03 - BARBARENO ROAD (CHUMASH NORD)', null, 'Head security', 'Raven'),
  ('LSMC', null, 'Kattalin', 'ESHEA', null, '9956', null, null, null, 'Raven'),
  ('LSMC', null, 'Tomas', 'DUGHLAS', null, '5546', null, null, null, 'Raven'),
  ('BAUN', null, 'Omar', 'JIMÉNEZ', null, '6970', null, 'à surveiller ?', null, 'Raven'),
  ('BB', null, 'Edouard', null, null, null, null, null, null, null),
  ('LSMC', null, 'Alexander', 'CLARK', null, '3864', null, 'récup stonks', 'Directeur', 'Raven'),
  ('STAND-BY', null, 'Stanislas', '???', null, '5404', null, null, null, 'Raven'),
  ('STONKS', null, 'Harold', 'REED', null, '8888', null, null, 'Chef d''équipe', 'Raven'),
  ('STONKS', null, 'John', 'SHELTON', null, '1856', null, null, 'Sénior', 'Raven'),
  ('BB', null, 'Diego', 'TEJADA', null, '7110', null, null, null, 'Raven'),
  ('BAUN', null, 'Alvaro', null, null, null, null, null, null, 'Raven'),
  ('STAND-BY', null, 'Nathan', 'CARVELL', null, '1826', null, null, 'Collègue', 'Raven'),
  ('BB', null, 'Connor', 'WELLS', null, '0982', null, null, 'Récup stonks', 'Raven'),
  ('STONKS', null, 'Joyce', 'RODRIGUEZ', null, '3040', null, null, 'Chef d''équipe', 'Raven'),
  ('TN', null, 'Alfie', 'KAHUANUI', null, '8700', null, 'Récup stonk', 'Patron', 'Raven'),
  ('STONKS', null, 'Osiris', 'RYDER', null, '2460', null, null, null, 'Raven'),
  ('MTP', null, 'Alexander', 'LOCKWOOD', null, '7071', null, null, 'Patron', 'Mason'),
  ('LSMC', null, 'John', 'KENT', null, '2969', null, null, 'Récup stonks', 'Raven'),
  ('UPW', null, 'Liam', '???', null, '8867', null, 'Récup stonk', 'Chef mais chef comr', 'Raven'),
  ('UPW', null, '???', '???', null, '2745', null, null, null, 'Raven'),
  ('UPW', null, 'Madison', 'BROOKS-FREDUCCI', null, '6436', null, null, null, 'Raven'),
  ('UPW', null, 'Tomasz', null, null, '2602', null, 'Récup stonk', null, 'Raven'),
  ('UPW', null, null, null, null, '2745', null, 'Récup stonk', null, 'Raven'),
  ('STAND-BY', null, '???', '???', null, '0997', null, null, null, 'Raven'),
  ('STONKS', null, 'Rosalya', 'BAXTER', null, '3484', null, null, 'Chef d''équipe', 'Raven'),
  ('BB', null, 'Michel', 'BETON', null, '8276', null, null, null, null),
  ('CJR', null, 'Julien', 'FACON', null, '5211', null, null, null, 'Raven'),
  ('BB', null, null, null, null, '9720', null, null, null, null),
  ('BB', null, 'Edward', 'CARELL', null, '5347', null, null, null, null),
  ('MTP', null, 'Adrian', 'SANDOVAL', null, '0496', null, null, 'Pompiste Sénior', 'Mason'),
  ('UPW', null, null, null, null, '2745', null, null, null, null),
  ('YN', 'FROST', 'Jake', 'PHOENIX', null, '6416', null, null, null, 'Raven'),
  ('YN', null, 'Malia', 'DE LA ROCHE ROEH', null, '8969', null, 'Sénatrice', 'Co-patronne', 'Raven'),
  ('YN', null, 'Joseph', 'NINO', null, null, null, null, null, 'Raven'),
  ('YN', null, 'Céleste', 'PANACÉA', null, '8208', null, 'Sénatrice', 'Patronne', 'Raven'),
  ('YN', null, 'Théo', 'PROCE', null, '5339', '09 MOVIE STAR WAY', 'Sénateur', null, 'Raven'),
  (null, 'G7', 'Han', 'CHENG', null, null, null, null, 'Chef de g7', 'Silas'),
  (null, 'G7', 'Shun', null, null, '3105', null, null, null, 'Raven'),
  ('PAWL', null, 'Hank', null, null, '0386', null, null, null, null)
)
insert into public.directory_contacts(job, entity, first_name, last_name, nickname, phone, address, notes, relation, contacted_by)
select coalesce(job, 'NON RENSEIGNÉ'), entity, coalesce(first_name, '???'), last_name, nickname, phone, address, notes, relation, contacted_by
from seed s
where not exists (
  select 1 from public.directory_contacts d
  where coalesce(d.job,'')=coalesce(s.job,'NON RENSEIGNÉ')
    and coalesce(d.entity,'')=coalesce(s.entity,'')
    and coalesce(d.first_name,'')=coalesce(s.first_name,'???')
    and coalesce(d.last_name,'')=coalesce(s.last_name,'')
    and coalesce(d.phone,'')=coalesce(s.phone,'')
);
