-- =========================================================
-- ATLAS RP v0.8.6 : DEMANDES DE SUPPRESSION
-- =========================================================

create table if not exists public.deletion_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  entity_type text not null
    check (entity_type in ('marker', 'zone')),

  entity_id bigint not null,
  entity_name text not null,

  requester_name text not null,
  reason text not null,

  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),

  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_by_name text
);

alter table public.deletion_requests enable row level security;

create unique index if not exists deletion_requests_one_pending_per_entity
  on public.deletion_requests (entity_type, entity_id)
  where status = 'pending';

create index if not exists deletion_requests_status_created_idx
  on public.deletion_requests (status, created_at);

drop policy if exists "Everyone can request deletion"
on public.deletion_requests;

create policy "Everyone can request deletion"
on public.deletion_requests
for insert
to anon, authenticated
with check (
  status = 'pending'
  and length(trim(entity_name)) between 1 and 150
  and length(trim(requester_name)) between 1 and 50
  and length(trim(reason)) between 1 and 1000
  and reviewed_at is null
  and reviewed_by is null
  and reviewed_by_name is null
);

drop policy if exists "Admins can read deletion requests"
on public.deletion_requests;

create policy "Admins can read deletion requests"
on public.deletion_requests
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can update deletion requests"
on public.deletion_requests;

create policy "Admins can update deletion requests"
on public.deletion_requests
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can delete deletion requests"
on public.deletion_requests;

create policy "Admins can delete deletion requests"
on public.deletion_requests
for delete
to authenticated
using ((select public.is_admin()));

do $$
begin
  alter publication supabase_realtime
  add table public.deletion_requests;
exception
  when duplicate_object then null;
end $$;
