"use strict";
(() => {
  const dialog=document.getElementById("directory-transfer-dialog"); if(!dialog)return;
  const form=document.getElementById("directory-transfer-form"), sourceInput=document.getElementById("directory-transfer-source"), idInput=document.getElementById("directory-transfer-id"), target=document.getElementById("directory-transfer-target"), summary=document.getElementById("directory-transfer-summary"), errorBox=document.getElementById("directory-transfer-error");
  const tables={members:"directory_members",contacts:"directory_contacts",law:"directory_law_enforcement"};
  const labels={members:"Membres",contacts:"Personnes rencontrées",law:"Forces de l’ordre"};
  document.addEventListener("click",e=>{const b=e.target.closest("[data-transfer-source][data-transfer-id]"); if(!b)return; sourceInput.value=b.dataset.transferSource;idInput.value=b.dataset.transferId;[...target.options].forEach(o=>o.disabled=o.value===sourceInput.value);target.value=[...target.options].find(o=>!o.disabled)?.value||"";summary.textContent=`La fiche sera déplacée de ${labels[sourceInput.value]} vers le tableau choisi. Les champs compatibles seront conservés.`;errorBox.hidden=true;dialog.showModal();});
  dialog.querySelectorAll("[data-transfer-close]").forEach(b=>b.onclick=()=>dialog.close()); dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close();});
  function memberPayload(r){return {grade_code:r.grade_code||"N1",first_name:r.first_name||"Inconnu",nickname:r.nickname||null,last_name:r.last_name||"Inconnu",identity_name:r.identity_name||[r.first_name,r.last_name].filter(Boolean).join(" ")||"Inconnu",rib:r.rib||null,phone:r.phone||null,address:r.address||null,housing_type:r.housing_type||null,district:r.district||null};}
  function contactPayload(r){return {job:r.job||r.service||"NON-RENSEIGNE",entity:r.entity||"NON-RENSEIGNE",first_name:r.first_name||"Inconnu",last_name:r.last_name||"Inconnu",nickname:r.nickname||null,phone:r.phone||null,address:r.address||null,notes:r.notes||null,relation:r.relation||null,contacted_by:r.contacted_by||null};}
  function lawPayload(r){return {service:r.service||"NON-RENSEIGNE",badge_number:r.badge_number||null,first_name:r.first_name||"Inconnu",last_name:r.last_name||"Inconnu",phone:r.phone||null,address:r.address||null,notes:r.notes||null,is_detective:Boolean(r.is_detective)};}
  form.addEventListener("submit",async e=>{e.preventDefault();const source=sourceInput.value,dest=target.value,id=idInput.value;if(!source||!dest||source===dest)return;const submit=form.querySelector('[type="submit"]');submit.disabled=true;errorBox.hidden=true;try{const {data:record,error:readError}=await supabaseClient.from(tables[source]).select("*").eq("id",id).single();if(readError)throw readError;const payload=dest==="members"?memberPayload(record):dest==="contacts"?contactPayload(record):lawPayload(record);const {error:createError}=await supabaseClient.from(tables[dest]).insert(payload);if(createError)throw createError;const {error:deleteError}=await supabaseClient.from(tables[source]).delete().eq("id",id);if(deleteError)throw new Error(`La nouvelle fiche a été créée, mais l’ancienne n’a pas pu être supprimée : ${deleteError.message}`);dialog.close();window.dispatchEvent(new CustomEvent("directory-transfer-complete"));location.reload();}catch(err){errorBox.textContent=err.message||"Déplacement impossible.";errorBox.hidden=false;}finally{submit.disabled=false;}});
})();
